service: hugo-backend

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: secretsmanager:GetSecretValue
      Resource: 
        - !Sub 'arn:aws:secretsmanager:${self:provider.region}:${self:custom.awsAccountId}:secret:hugo/jwt'
  environment:
    USERS_TABLE: Users
    GROUPS_TABLE: Groups
    TASKS_TABLE: Tasks
    TOKEN_DENYLIST_TABLE: TokenDenylist

resources:
  - ${file(config/resources/dynamoDb.yml)}

functions:
  registerUser:
    handler: src/adapters/lambda/registerUser.handler
    events:
      - http:
          method: post
          path: users/register
  loginUser:
    handler: src/adapters/lambda/loginUser.handler
    events:
      - http:
          method: post
          path: users/login
  logoutUser:
    handler: src/adapters/lambda/logoutUser.handler
    events:
      - http:
          method: post
          path: users/logout
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  awsAccountId: '064339330257'
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
